# GitHub Action for Jekyll
#
# Runs jekyll build on master and pushes output to gh-pages branch.
# (Then GitHub deploys that static content.)

name: Build & Deploy to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  github-pages:
    runs-on: ubuntu-latest
    container: ruby:3.4.9-bookworm
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}

      - name: Install Ruby dependencies.
        run: |
          gem install bundler
          bundle install --path vendor/bundle

      - name: Build static site with Jekyll.
        run: bundle exec jekyll build

      - name: Deploy static site to gh-pages branch.
        uses: peaceiris/actions-gh-pages@4f9cc6602d3f66b9c108549d475ec49e8ef4d45e # v4.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
